# Generated by Django 4.2 on 2026-03-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_coupon_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promoted',
            field=models.BooleanField(default=False, help_text='Owner promoted this product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
