# Generated by Django 4.2 on 2026-03-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_dimensions_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False, help_text='Owner must approve before showing'),
        ),
    ]
