# Generated by Django 4.2 on 2026-04-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_review_approved'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS store_product_temp;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE store_product_temp AS SELECT 
                id, name, slug, description, price, stock_quantity, category_id, 
                images, additional_images, material, is_featured, is_promoted, 
                is_available, created_at, updated_at 
            FROM store_product;
            """,
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE store_product;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE store_product (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(200) NOT NULL,
                slug VARCHAR(50) NOT NULL UNIQUE,
                description TEXT NOT NULL,
                price DECIMAL(10, 2) NOT NULL,
                stock_quantity INTEGER NOT NULL,
                category_id INTEGER NOT NULL REFERENCES store_category(id),
                images VARCHAR(100) NULL,
                additional_images VARCHAR(100) NULL,
                material VARCHAR(100) NULL,
                is_featured BOOL NOT NULL,
                is_promoted BOOL NOT NULL,
                is_available BOOL NOT NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL
            );
            """,
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO store_product (
                id, name, slug, description, price, stock_quantity, category_id,
                images, additional_images, material, is_featured, is_promoted,
                is_available, created_at, updated_at
            ) SELECT 
                id, name, slug, description, price, stock_quantity, category_id,
                images, additional_images, material, is_featured, is_promoted,
                is_available, created_at, updated_at
            FROM store_product_temp;
            """,
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE store_product_temp;",
            reverse_sql="",
        ),
    ]
